name: ci

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 23 15 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          tags: ghcr.io/bradym/familycodex/site:latest
